package com.pm.patientservice.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotNull;

import java.time.LocalDate;
import java.util.UUID;

// class to store all the fields associated with a patient
// we add the entity tag to tell spring that this is an entity class ,and it is used to persist data in the database
@Entity
public class Patient {
    // need to create a field called id of UUID type that is generated by the system
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;

    // Non nulls add persistence level validation

    @NotNull
    private String name;

    @NotNull
    private String address;

    // this provides additional validation by preventing duplicate emails to be entered
    @NotNull
    @Email
    @Column(unique = true)
    private String email;

    // LocalDate is a dateTime object, avoids us from storing a date as a String
    @NotNull
    private LocalDate dateOfBirth;

    @NotNull
    private LocalDate registeredDate;

    // getters and setters for encapsulation
    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public LocalDate getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(LocalDate dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public LocalDate getRegisteredDate() {
        return registeredDate;
    }

    public void setRegisteredDate(LocalDate registeredDate) {
        this.registeredDate = registeredDate;
    }
}
