###
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe",
  "email": "test@example.com",
  "address": "123 main street",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "1995-09-09"
}

### the values we have specified just specify an example template so it just needs to be of the correct spring type
### since this is a post type of request, we need to tell the server what to expect
###